'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.join(__dirname, '..');
const rendererDir = path.join(root, 'src', 'renderer');
const checkOnly = process.argv.slice(2).includes('--check');
const unknownArguments = process.argv.slice(2).filter(argument => argument !== '--check');

if (unknownArguments.length > 0) {
  throw new Error(`Unknown renderer build argument(s): ${unknownArguments.join(', ')}`);
}

const htmlFragments = [
  'shell',
  'login',
  'overview',
  'bot-setup',
  'combat',
  'auto-farm-general',
  'advanced',
  'auto-farm-workspace',
  'progression',
  'battle-pass',
  'adventure-quests',
  'custom-runs',
  'boss-hunt',
  'targets',
  'looting',
  'statistics',
  'logs',
  'dialogs',
  'footer'
];

const javascriptUnits = [
  '00-i18n',
  '00-core',
  '01-dom',
  '02-farm',
  '03-catalog-auto-farm',
  '04-progression-resources',
  '05-combat-config',
  '05a-cube-pvp',
  '05b-power-crystals',
  '05c-combat-profiles',
  '06-history',
  '07-auto-farm',
  '08-targets',
  '09-looting',
  '09a-statistics',
  '09b-objectives',
  '09c-boss-hunt',
  '09e-custom-runs',
  '10-navigation-settings',
  '11-session-telemetry',
  '12-chapters',
  '13-bootstrap'
];

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), 'utf8');
}

function countOccurrences(source, value) {
  return source.split(value).length - 1;
}

function assertManifestDirectory(relativeDirectory, extension, expectedNames) {
  const actual = fs.readdirSync(path.join(root, relativeDirectory))
    .filter(name => name.endsWith(extension))
    .map(name => name.slice(0, -extension.length))
    .sort();
  const expected = [...expectedNames].sort();
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(`${relativeDirectory} does not match its renderer manifest`);
  }
}

function composeHtml() {
  assertManifestDirectory('src/renderer/views', '.html', htmlFragments);
  let output = read('src/renderer/index.template.html');
  for (const name of htmlFragments) {
    const marker = `<!-- @veybot-include:${name} -->`;
    if (countOccurrences(output, marker) !== 1) {
      throw new Error(`Renderer template must contain exactly one ${marker} marker`);
    }
    const fragment = read(`src/renderer/views/${name}.html`);
    if (/<script\b/i.test(fragment)) throw new Error(`${name}.html must not own script tags`);
    if (/\son[a-z]+\s*=/i.test(fragment)) throw new Error(`${name}.html must not contain inline event handlers`);
    output = output.replace(marker, fragment);
  }
  if (/@veybot-include:/.test(output)) throw new Error('Renderer template contains an unknown include marker');
  return output.replace('<!DOCTYPE html>\n', '<!DOCTYPE html>\n<!-- Generated by scripts/buildRenderer.js; edit index.template.html or views/*.html. -->\n');
}

function composeJavaScript() {
  assertManifestDirectory('src/renderer/app', '.js', javascriptUnits);
  const units = javascriptUnits.map(name => {
    const source = read(`src/renderer/app/${name}.js`);
    new vm.Script(source, { filename: `${name}.js` });
    return source;
  });
  const bootstrapOwners = javascriptUnits.filter((name, index) => units[index].includes("document.addEventListener('DOMContentLoaded'"));
  if (JSON.stringify(bootstrapOwners) !== JSON.stringify(['13-bootstrap'])) {
    throw new Error('Only 13-bootstrap.js may own DOMContentLoaded initialization');
  }
  const catalogs = Object.fromEntries(['en', 'de', 'fr'].map(language => [language,
    JSON.parse(read('src/renderer/locales/' + language + '.json'))]));
  const keys = Object.keys(catalogs.en).sort();
  for (const language of ['de', 'fr']) {
    if (JSON.stringify(Object.keys(catalogs[language]).sort()) !== JSON.stringify(keys)) throw new Error('Incomplete interface catalog: ' + language);
  }
  return '/* Generated by scripts/buildRenderer.js; edit app/*.js or locales/*.json. */\n'
    + 'const UI_TRANSLATIONS = ' + JSON.stringify(catalogs) + ';\n' + units.join('');
}

function assertUniqueIds(html) {
  const counts = new Map();
  for (const match of html.matchAll(/\bid=["']([^"']+)["']/g)) {
    counts.set(match[1], (counts.get(match[1]) || 0) + 1);
  }
  const duplicates = [...counts].filter(([, count]) => count > 1).map(([id]) => id);
  if (duplicates.length > 0) throw new Error(`Duplicate renderer ID(s): ${duplicates.join(', ')}`);
  return new Set(counts.keys());
}

function assertDomReferences(html, javascript) {
  const ids = assertUniqueIds(html);
  const missing = new Set();
  for (const match of javascript.matchAll(/document\.getElementById\(\s*(["'])([^"']+)\1\s*\)/g)) {
    if (!ids.has(match[2])) missing.add(match[2]);
  }
  if (missing.size > 0) throw new Error(`Static renderer DOM reference(s) are missing: ${[...missing].sort().join(', ')}`);

  const requiredViews = [
    'viewLogin',
    'viewHome',
    'viewAutoFarm',
    'viewEnergyFarm',
    'viewNPCConfig',
    'viewLootConfig',
    'viewStatistics',
    'viewBattlePass',
    'viewAdventureQuests',
    'viewBossHunt',
    'viewConsole'
  ];
  const missingViews = requiredViews.filter(id => !ids.has(id));
  if (missingViews.length > 0) throw new Error(`Renderer view(s) are missing: ${missingViews.join(', ')}`);
}

function assertSecurityAndOrder(html) {
  const csp = html.match(/<meta\s+http-equiv=["']Content-Security-Policy["'][\s\S]*?content=(["'])([\s\S]*?)\1[^>]*>/i)?.[2] || '';
  if (!csp.includes("script-src 'self'") || !csp.includes("connect-src 'none'")) {
    throw new Error('Renderer CSP must keep local-only scripts and deny renderer network connections');
  }

  const scriptPaths = [...html.matchAll(/<script\s+src=["']([^"']+)["'][^>]*><\/script>/g)].map(match => match[1]);
  const expected = [
    '../../node_modules/lucide/dist/umd/lucide.min.js',
    'monsterStatsView.js',
    'app.js'
  ];
  if (JSON.stringify(scriptPaths) !== JSON.stringify(expected)) {
    throw new Error(`Renderer script order changed: ${scriptPaths.join(' -> ')}`);
  }
}

function assertOutput(targetPath, output) {
  if (!checkOnly) {
    const temporaryPath = `${targetPath}.tmp-${process.pid}`;
    fs.writeFileSync(temporaryPath, output);
    fs.renameSync(temporaryPath, targetPath);
    return;
  }
  const current = fs.readFileSync(targetPath, 'utf8');
  if (current !== output) {
    throw new Error(`${path.relative(root, targetPath)} is stale; run npm run build:renderer`);
  }
}

const html = composeHtml();
const javascript = composeJavaScript();
assertDomReferences(html, javascript);
assertSecurityAndOrder(html);
assertOutput(path.join(rendererDir, 'index.html'), html);
assertOutput(path.join(rendererDir, 'app.js'), javascript);

process.stdout.write(checkOnly ? 'Renderer generated files are current.\n' : 'Renderer generated files updated.\n');
